### PR TITLE
WIP LPS-122779 Apply shortCutButton in EditAppStepContent

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:app-build

**Comment by gabrielpramos** [comment]
ci:test:sf
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielpramos** [comment]
rebase done and pr sent to @liferay-workflow in [pr-104](https://github.com/liferay-workflow/liferay-portal/pull/104)

**Pull request closed without merging**
