### PR TITLE
LRAC-9811 SF

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:forward

**Comment by gabrielpramos** [comment]
ci:stop

**Comment by gabrielpramos** [comment]
ci:forward

**Comment by gabrielpramos** [comment]
ci:forward

**Comment by kienD** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
https://github.com/gabrielpramos/liferay-portal/pull/146

**Pull request closed without merging**
