### PR TITLE
LPS-116718 Change function name

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:forward

**Comment by gabrielpramos** [comment]
ci:forward

**Comment by inacionery** [comment]
ci:stop

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Forwarded to https://github.com/inacionery/liferay-portal/pull/903

**Comment by inacionery** [comment]
ci:close

**Comment by inacionery** [comment]
ci:stop

**Pull request closed without merging**
