### PR TITLE
LPS-110941 Reduce code smells from components

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:stable

**Comment by albinojunior** [comment]
ci:stop

**Comment by gabrielpramos** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
