### PR TITLE
LPS-97666 | LPS-104293 Move ViewAllSteps button to Footer of PerformanceByStepCard

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
Just started reviewing :)

**Pull request closed without merging**
