### PR TITLE
LPS-107142 Apply pagination on bulk reassign modal steps

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
@gabrielpramos this PR depends on another [PR](https://github.com/gabrielpramos/liferay-portal/pull/35) that is pending merge.

**Comment by gabrielpramos** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielpramos** [comment]
approved and forwarded to @inacionery

**Pull request closed without merging**
