### PR TITLE
LPS-103759 | LPS-103891 Update tests to cover compound components structures and route params passing

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
Just started reviewing :)

**Comment by gabrielpramos** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/289.

**Comment by gabrielpramos** [comment]
Just started reviewing :)

**Pull request closed without merging**
