### PR TITLE
LPS-111264 | LPS-112846 buildLang

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
ci:forward

**Comment by inacionery** [comment]
ci:forward

**Comment by inacionery** [comment]
ci:forward

**Comment by gabrielpramos** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
